// ui/src/utils/reportExport.ts
// Centralized report export utilities

import {
  TEXT_FILTERS,
  MARKDOWN_FILTERS,
  HTML_FILTERS,
  JSON_FILTERS,
  type DialogFilter,
} from "../api/dialogs";
import type { ReportFormat } from "../api/reports";

export type ExportFormat = "text" | "markdown" | "html-screen" | "html-print" | "json";

export const FORMAT_EXTENSIONS: Record<ExportFormat, string> = {
  text: ".txt",
  markdown: ".md",
  "html-screen": ".html",
  "html-print": ".html",
  json: ".json",
};

export const FORMAT_DESCRIPTIONS: Record<ExportFormat, string> = {
  text: "Plain text report with visual formatting",
  markdown: "Structured markdown with tables and sections",
  "html-screen": "Rich HTML with dark theme colors and styling",
  "html-print": "Light theme HTML optimized for printing or PDF export",
  json: "Raw JSON data for programmatic processing",
};

export const FORMAT_OPTIONS: { value: ExportFormat; label: string }[] = [
  { value: "text", label: "Text" },
  { value: "markdown", label: "Markdown" },
  { value: "html-screen", label: "HTML (Screen Optimised)" },
  { value: "html-print", label: "HTML (Print Optimised)" },
  { value: "json", label: "JSON" },
];

/**
 * Get date prefix in reverse ISO format (YYYYMMDD-)
 */
export function getDatePrefix(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}${month}${day}-`;
}

/**
 * Get full filename with date prefix and correct extension
 */
export function getFullFilename(filename: string, format: ExportFormat): string {
  const ext = FORMAT_EXTENSIONS[format];
  const datePrefix = getDatePrefix();
  const prefixedFilename = filename.startsWith(datePrefix) ? filename : `${datePrefix}${filename}`;
  return prefixedFilename.endsWith(ext) ? prefixedFilename : `${prefixedFilename}${ext}`;
}

/**
 * Get dialog filter for a given export format
 */
export function getFilterForFormat(format: ExportFormat): DialogFilter[] {
  switch (format) {
    case "text":
      return TEXT_FILTERS;
    case "markdown":
      return MARKDOWN_FILTERS;
    case "html-screen":
    case "html-print":
      return HTML_FILTERS;
    case "json":
      return JSON_FILTERS;
  }
}

/** Milliseconds to one decimal place, in seconds from a second up. */
export function formatMs(ms: number): string {
  return Math.round(ms * 10) >= 10_000 ? `${(ms / 1000).toFixed(1)}s` : `${ms.toFixed(1)}ms`;
}

/** `formatMs`, or a dash for a period that was never seen. */
export function formatOptionalMs(ms: number | null): string {
  return ms === null ? "—" : formatMs(ms);
}

/**
 * A report in an export format: text and Markdown as Rust renders them, HTML as
 * Rust's body inside the screen or print theme. JSON is the caller's own data.
 */
export async function renderReport(
  format: Exclude<ExportFormat, "json">,
  title: string,
  render: (format: ReportFormat) => Promise<string>,
): Promise<string> {
  if (format === "text" || format === "markdown") return render(format);
  const print = format === "html-print";
  const preamble = print
    ? `<div class="print-instructions"><strong>To save as PDF:</strong> Use your browser's Print function (Ctrl+P / Cmd+P) and select "Save as PDF" as the destination.</div>\n`
    : "";
  return `<!DOCTYPE html>
<html lang="en-AU">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)}</title>
<style>${print ? PRINT_THEME : SCREEN_THEME}</style>
</head>
<body>
<div class="container">
${preamble}${await render("html")}<div class="footer">Generated by WireTAP</div>
</div>
</body>
</html>
`;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

const SCREEN_THEME = `
  :root {
    --bg-primary: #0f172a;
    --bg-secondary: #1e293b;
    --text-primary: #f1f5f9;
    --text-secondary: #94a3b8;
    --accent-purple: #a855f7;
    --accent-pink: #ec4899;
    --accent-cyan: #22d3ee;
    --accent-green: #22c55e;
    --border: #475569;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg-primary); color: var(--text-primary); line-height: 1.6; padding: 2rem;
  }
  .container { max-width: 1200px; margin: 0 auto; }
  h1 {
    font-size: 2rem; margin-bottom: 1rem;
    background: linear-gradient(135deg, var(--accent-purple), var(--accent-pink));
    -webkit-background-clip: text; -webkit-text-fill-color: transparent;
  }
  h2 { font-size: 1.5rem; margin: 2rem 0 1rem; color: var(--accent-purple); }
  h3 { font-size: 1.1rem; margin: 0 0 0.5rem; color: var(--accent-purple); font-family: monospace; }
  h4, h5, h6 { font-size: 1rem; margin: 1rem 0 0.5rem; color: var(--text-primary); }
  section.level-3 {
    background: var(--bg-secondary); border: 1px solid var(--border); border-radius: 10px;
    padding: 12px; margin: 16px 0;
  }
  section.level-4, section.level-5, section.level-6 {
    border-left: 4px solid var(--accent-green); padding: 0 0 0 10px; margin: 10px 0;
  }
  section.level-5 { border-left-color: var(--accent-cyan); }
  section.level-6 { border-left-color: var(--accent-purple); }
  table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; font-size: 0.875rem; }
  th, td { padding: 0.4rem 0.5rem; text-align: left; border-bottom: 1px solid var(--border); vertical-align: top; }
  th { color: var(--text-secondary); font-weight: 500; white-space: nowrap; }
  table.fields { width: auto; }
  table.fields th, table.fields td { border: none; padding: 0.1rem 1rem 0.1rem 0; }
  code { font-family: monospace; color: var(--text-primary); }
  ul { margin: 0.5rem 0; padding-left: 1.5rem; color: var(--text-secondary); }
  .badge { display: inline-block; padding: 0.1rem 0.4rem; border-radius: 4px; font-size: 0.75rem; font-weight: 500; }
  .conf-high { background: rgba(34, 197, 94, 0.2); color: #22c55e; }
  .conf-medium { background: rgba(59, 130, 246, 0.2); color: #60a5fa; }
  .conf-low { background: rgba(234, 179, 8, 0.2); color: #facc15; }
  .conf-none { background: rgba(148, 163, 184, 0.2); color: #94a3b8; }
  .end-default { background: rgba(100, 116, 139, 0.3); color: #cbd5e1; }
  .end-override { background: rgba(239, 68, 68, 0.2); color: #f87171; }
  .footer {
    margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border);
    text-align: center; color: var(--text-secondary); font-size: 0.875rem;
  }
`;

const PRINT_THEME = `
  :root {
    --text-primary: #1e293b;
    --text-secondary: #64748b;
    --text-muted: #94a3b8;
    --border: #e2e8f0;
    --bg-light: #f8fafc;
    --accent: #7c3aed;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;
    color: var(--text-primary); line-height: 1.5; padding: 20mm; max-width: 210mm; margin: 0 auto;
  }
  @media print {
    body { padding: 0; max-width: none; }
    @page { margin: 15mm; size: A4; }
    .print-instructions { display: none; }
  }
  h1 { font-size: 24pt; font-weight: 700; color: var(--accent); margin-bottom: 8pt; border-bottom: 2pt solid var(--accent); padding-bottom: 8pt; }
  h2 { font-size: 14pt; font-weight: 600; margin: 16pt 0 8pt; border-bottom: 1pt solid var(--border); padding-bottom: 4pt; }
  h3 { font-size: 12pt; font-weight: 600; color: var(--accent); margin: 0 0 4pt; font-family: 'SF Mono', Monaco, 'Courier New', monospace; }
  h4, h5, h6 { font-size: 10pt; font-weight: 600; color: var(--text-secondary); margin: 8pt 0 4pt; }
  section.level-3 { border: 1pt solid var(--border); border-radius: 4pt; padding: 8pt; margin: 10pt 0; page-break-inside: avoid; }
  section.level-4, section.level-5, section.level-6 { border-left: 2pt solid #16a34a; padding-left: 6pt; margin: 6pt 0; }
  section.level-5 { border-left-color: #0891b2; }
  section.level-6 { border-left-color: #9333ea; }
  table { width: 100%; border-collapse: collapse; font-size: 8pt; margin: 4pt 0; }
  th, td { padding: 3pt 4pt; text-align: left; border: 0.5pt solid var(--border); vertical-align: top; }
  th { background: var(--bg-light); font-weight: 600; color: var(--text-secondary); }
  table.fields { width: auto; }
  table.fields th, table.fields td { border: none; background: none; padding: 1pt 10pt 1pt 0; }
  code { font-family: 'SF Mono', Monaco, 'Courier New', monospace; font-size: 7pt; }
  ul { margin: 4pt 0; padding-left: 16pt; font-size: 9pt; color: var(--text-secondary); }
  .badge { display: inline-block; font-size: 7pt; padding: 1pt 4pt; border-radius: 2pt; font-weight: 500; }
  .conf-high { background: #dcfce7; color: #166534; }
  .conf-medium { background: #dbeafe; color: #1e40af; }
  .conf-low { background: #fef3c7; color: #92400e; }
  .conf-none { background: #f1f5f9; color: #475569; }
  .end-default { background: #e2e8f0; color: #475569; }
  .end-override { background: #fee2e2; color: #b91c1c; }
  .footer { margin-top: 20pt; padding-top: 10pt; border-top: 1pt solid var(--border); text-align: center; font-size: 8pt; color: var(--text-muted); }
  .print-instructions { background: #eff6ff; border: 1pt solid #bfdbfe; border-radius: 4pt; padding: 10pt; margin: 12pt 0; font-size: 9pt; color: #1e40af; }
`;
