// crates/wiretap-app/src/report/mod.rs
//
// The export reports, worded in en-AU: each report builds one `Doc`, written as
// plain text, Markdown, or an HTML body the frontend wraps in its theme. The
// structure is the lib's (`CatalogSummary`, `changes_counts`, `order_totals`).

pub mod catalog;
pub mod changes;
pub mod held;
#[cfg(test)]
mod goldens;
mod notes;
pub mod order;

use serde::Deserialize;
use wiretap_analysis::FrameKey;
use wiretap_decode::frame_id::format_frame_id;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ReportFormat {
    Text,
    Markdown,
    Html,
}

pub struct Doc {
    title: String,
    blocks: Vec<Block>,
}

pub enum Block {
    Section(String, Vec<Block>),
    Fields(Vec<(&'static str, String)>),
    Table(Vec<&'static str>, Vec<Vec<Cell>>),
    List(Vec<String>),
}

pub enum Cell {
    Plain(String),
    Code(String),
    /// Text the HTML marks with a badge class.
    Tag(String, String),
}

impl Block {
    fn is_empty(&self) -> bool {
        match self {
            Block::Section(..) => false,
            Block::Fields(f) => f.is_empty(),
            Block::Table(_, rows) => rows.is_empty(),
            Block::List(items) => items.is_empty(),
        }
    }
}

impl Cell {
    fn text(&self) -> &str {
        match self {
            Cell::Plain(s) | Cell::Code(s) | Cell::Tag(s, _) => s,
        }
    }
}

impl From<String> for Cell {
    fn from(s: String) -> Self {
        Cell::Plain(s)
    }
}

impl From<&str> for Cell {
    fn from(s: &str) -> Self {
        Cell::Plain(s.into())
    }
}

const WIDTH: usize = 80;
const FOOTER: &str = "Generated by WireTAP";

impl Doc {
    pub fn render(&self, format: ReportFormat) -> String {
        let mut out = String::new();
        match format {
            ReportFormat::Text => {
                let rule = "═".repeat(WIDTH);
                out += &format!("{rule}\n  {}\n{rule}\n", self.title.to_uppercase());
                text_blocks(&mut out, &self.blocks, 1);
                out += &format!("\n{rule}\n  {FOOTER}\n{rule}\n");
            }
            ReportFormat::Markdown => {
                out += &format!("# {}\n", self.title);
                markdown_blocks(&mut out, &self.blocks, 2);
                out += &format!("\n---\n\n*{FOOTER}*\n");
            }
            ReportFormat::Html => {
                out += &format!("<h1>{}</h1>\n", escape(&self.title));
                html_blocks(&mut out, &self.blocks, 2);
            }
        }
        out
    }
}

fn text_blocks(out: &mut String, blocks: &[Block], depth: usize) {
    let indent = "  ".repeat(depth.saturating_sub(1).max(1));
    for block in blocks.iter().filter(|b| !b.is_empty()) {
        out.push('\n');
        match block {
            Block::Section(title, inner) => {
                match depth {
                    1 => *out += &format!("{}\n{}\n", title.to_uppercase(), "─".repeat(WIDTH)),
                    2 => {
                        let head = format!("── {title} ");
                        let fill = WIDTH.saturating_sub(head.chars().count());
                        *out += &format!("{head}{}\n", "─".repeat(fill));
                    }
                    _ => *out += &format!("{indent}{title}\n"),
                }
                text_blocks(out, inner, depth + 1);
            }
            Block::Fields(fields) => {
                let width = fields.iter().map(|(l, _)| l.chars().count()).max().unwrap_or(0) + 1;
                for (label, value) in fields {
                    *out += &format!("{indent}{:width$} {value}\n", format!("{label}:"));
                }
            }
            Block::Table(header, rows) => {
                let widths: Vec<usize> = (0..header.len())
                    .map(|c| {
                        rows.iter()
                            .map(|r| r[c].text().chars().count())
                            .chain([header[c].chars().count()])
                            .max()
                            .unwrap_or(0)
                    })
                    .collect();
                let line = |cells: Vec<&str>| {
                    let padded: Vec<String> =
                        cells.iter().zip(&widths).map(|(c, w)| format!("{c:w$}")).collect();
                    format!("{indent}{}\n", padded.join("  ").trim_end())
                };
                *out += &line(header.clone());
                let total = widths.iter().sum::<usize>() + 2 * widths.len().saturating_sub(1);
                *out += &format!("{indent}{}\n", "-".repeat(total));
                for row in rows {
                    *out += &line(row.iter().map(Cell::text).collect());
                }
            }
            Block::List(items) => {
                for item in items {
                    *out += &format!("{indent}- {item}\n");
                }
            }
        }
    }
}

fn markdown_blocks(out: &mut String, blocks: &[Block], level: usize) {
    for block in blocks.iter().filter(|b| !b.is_empty()) {
        out.push('\n');
        match block {
            Block::Section(title, inner) => {
                *out += &format!("{} {title}\n", "#".repeat(level.min(6)));
                markdown_blocks(out, inner, level + 1);
            }
            Block::Fields(fields) => {
                for (label, value) in fields {
                    *out += &format!("- **{label}:** {value}\n");
                }
            }
            Block::Table(header, rows) => {
                *out += &format!("| {} |\n", header.join(" | "));
                *out += &format!("|{}\n", "---|".repeat(header.len()));
                for row in rows {
                    let cells: Vec<String> = row
                        .iter()
                        .map(|c| match c {
                            Cell::Code(s) if !s.is_empty() => format!("`{s}`"),
                            c => c.text().replace('|', "\\|"),
                        })
                        .collect();
                    *out += &format!("| {} |\n", cells.join(" | "));
                }
            }
            Block::List(items) => {
                for item in items {
                    *out += &format!("- {item}\n");
                }
            }
        }
    }
}

fn html_blocks(out: &mut String, blocks: &[Block], level: usize) {
    for block in blocks.iter().filter(|b| !b.is_empty()) {
        match block {
            Block::Section(title, inner) => {
                let h = level.min(6);
                *out += &format!("<section class=\"level-{h}\">\n<h{h}>{}</h{h}>\n", escape(title));
                html_blocks(out, inner, level + 1);
                *out += "</section>\n";
            }
            Block::Fields(fields) => {
                *out += "<table class=\"fields\">\n";
                for (label, value) in fields {
                    *out += &format!("<tr><th>{label}</th><td>{}</td></tr>\n", escape(value));
                }
                *out += "</table>\n";
            }
            Block::Table(header, rows) => {
                let head: String = header.iter().map(|h| format!("<th>{h}</th>")).collect();
                *out += &format!("<table>\n<thead><tr>{head}</tr></thead>\n<tbody>\n");
                for row in rows {
                    let cells: String = row
                        .iter()
                        .map(|c| match c {
                            Cell::Plain(s) => format!("<td>{}</td>", escape(s)),
                            Cell::Code(s) => format!("<td><code>{}</code></td>", escape(s)),
                            Cell::Tag(s, class) => {
                                format!("<td><span class=\"badge {class}\">{}</span></td>", escape(s))
                            }
                        })
                        .collect();
                    *out += &format!("<tr>{cells}</tr>\n");
                }
                *out += "</tbody>\n</table>\n";
            }
            Block::List(items) => {
                let items: String = items.iter().map(|i| format!("<li>{}</li>", escape(i))).collect();
                *out += &format!("<ul>{items}</ul>\n");
            }
        }
    }
}

fn escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// `n` with en-AU digit grouping: `12,345`.
pub fn grouped(n: usize) -> String {
    let digits = n.to_string();
    let mut out = String::new();
    for (i, d) in digits.chars().enumerate() {
        if i > 0 && (digits.len() - i).is_multiple_of(3) {
            out.push(',');
        }
        out.push(d);
    }
    out
}

/// `1 frame`, `2,048 frames`.
pub fn count(n: usize, noun: &str) -> String {
    format!("{} {noun}{}", grouped(n), if n == 1 { "" } else { "s" })
}

/// A duration to one decimal place, in seconds from a second up.
pub fn ms(value: f64) -> String {
    if (value * 10.0).round() >= 10_000.0 {
        format!("{:.1} s", value / 1000.0)
    } else {
        format!("{value:.1} ms")
    }
}

pub fn optional_ms(value: Option<f64>) -> String {
    value.map_or_else(|| "—".into(), ms)
}

pub fn protocol_label(protocol: &str) -> String {
    match protocol {
        "can" => "CAN".into(),
        "canfd" => "CAN FD".into(),
        "modbus" => "Modbus".into(),
        "modbus_rtu" => "Modbus RTU".into(),
        "serial" => "Serial".into(),
        other => other.into(),
    }
}

/// A frame as its protocol names it: a CAN id in hex, a Modbus register in
/// decimal, an RTU message as unit/function, a serial id as its one or two bytes.
pub fn frame_label(protocol: &str, key: FrameKey) -> String {
    let id = key.frame_id;
    match protocol {
        "modbus" => id.to_string(),
        "modbus_rtu" => format!("{}/0x{:02X}", id >> 8 & 0xFF, id & 0xFF),
        "serial" if id <= 0xFF => format!("0x{id:02X}"),
        "serial" => format!("0x{id:04X}"),
        _ => format_frame_id(id, key.is_extended),
    }
}

/// Protocols in the order the reports list them.
pub fn protocol_rank(protocol: &str) -> u8 {
    match protocol {
        "can" | "canfd" => 0,
        "modbus" | "modbus_rtu" => 1,
        "serial" => 2,
        _ => 3,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn numbers_group_in_threes() {
        assert_eq!(grouped(0), "0");
        assert_eq!(grouped(999), "999");
        assert_eq!(grouped(1000), "1,000");
        assert_eq!(grouped(1_234_567), "1,234,567");
        assert_eq!(count(1, "frame"), "1 frame");
        assert_eq!(count(2048, "frame"), "2,048 frames");
    }

    #[test]
    fn a_duration_that_rounds_to_a_second_reads_in_seconds() {
        assert_eq!(ms(999.94), "999.9 ms");
        assert_eq!(ms(999.95), "1.0 s");
        assert_eq!(ms(12_345.0), "12.3 s");
    }

    #[test]
    fn each_protocol_labels_its_frames_its_own_way() {
        let key = |id, ext| FrameKey::new(id, ext);
        assert_eq!(frame_label("can", key(0x10, false)), "0x010");
        assert_eq!(frame_label("can", key(0x10, true)), "0x00000010");
        assert_eq!(frame_label("serial", key(0x10, false)), "0x10");
        assert_eq!(frame_label("serial", key(0x1234, false)), "0x1234");
        assert_eq!(frame_label("modbus", key(40001, false)), "40001");
        assert_eq!(frame_label("modbus_rtu", key(0x0103, false)), "1/0x03");
    }

    #[test]
    fn markdown_escapes_pipes_and_html_escapes_markup() {
        let doc = Doc {
            title: "T".into(),
            blocks: vec![Block::Table(vec!["a"], vec![vec![Cell::Plain("x|<y>".into())]])],
        };
        assert!(doc.render(ReportFormat::Markdown).contains("| x\\|<y> |"));
        assert!(doc.render(ReportFormat::Html).contains("<td>x|&lt;y&gt;</td>"));
    }
}
